dist: xenial
language: python
cache: pip
env:
- >
  TEST_CMD="pytest test/ -vv --run-e2e --doctest-modules"
  BROKER_URL="localhost:9092"
  ZOOKEEPER_URL="localhost:2181"
  SCHEMA_REGISTRY_URL="localhost:8081"
before_install:
- wget http://packages.confluent.io/archive/5.2/confluent-community-5.2.1-2.12.tar.gz -O confluent-community.tgz
- mkdir -p confluent-community && tar xzf confluent-community.tgz -C confluent-community --strip-components 1
- confluent-community/bin/zookeeper-server-start -daemon confluent-community/etc/kafka/zookeeper.properties
- bash -c "scripts/wait-for-it.sh ${ZOOKEEPER_URL} -t 60"
- confluent-community/bin/kafka-server-start -daemon confluent-community/etc/kafka/server.properties
- bash -c "scripts/wait-for-it.sh ${BROKER_URL} -t 60"
- confluent-community/bin/schema-registry-start -daemon confluent-community/etc/schema-registry/schema-registry.properties
- bash -c "scripts/wait-for-it.sh ${SCHEMA_REGISTRY_URL} -t 60"
install:
- pip install coverage coveralls flake8 pipenv
- pipenv install --system --dev
script:
- "$TEST_CMD"
after_success:
- coveralls
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: smoroCy0PngSmLz0cAOKKQdAH/4x5gigxjiMe6uNDOVgRTyfMceoTGwNcuw3+iw8NJUTVGxt+1auLCXRxO1fK9Vv75j077BqMrwCfEnBE87xFBOQ1ht4OoYsGbZYG24BGGXSQC2XWok1pts8531AivMuN5epVbVHmYAaLFvspjVV1okTbmDqbi1Cipuckz9gtTq2lvvBYHmFwqEEBGwA1NlNisqNBBgYK9+Jcc9oj+ZHUDs65vB9vOJp0VxR/9cw9KoupHu3OGaPcbaVlTJGF4IAapYAbgxU2ebRkMGY0A0uDdt8oPZS2n3DH79JXigiEQ8gir1LrVXlliLlJU85HIT6NCyxDhzegP3dANEfjOg44Dqy0TekT7/3n3/rq0RZftUhz/3Y5JXK7/HtG7DcJzPuCJi8RGen3jjD6D0960Of75EDab5pIaC0Y4tV8QT3VzRy0lORHk9i34x77v2ujYAvyr4XRjJXyd6U0NQkLpkcT5Cb1BGGyAjfLGC8oUakRgb3dvyJaPnE2/vIHtAq8JtEetIhlXDXe4nvUAAtuDQ7dL+v5x7vfuuJYLLsNCMRq+zd6+DlaxMEVyXlMivAmz3P19PFoGy8O1cb05Z0BcQVD8xjQiitPMpp9G9VqjFgLmSecwClmWw8qgqVpOGNy3eOBvAeQVr6MbY1zGXjEPw=
matrix:
  include:
  - name: black
    python: 3.8
    before_install: []
    env:
    - TEST_CMD="black --check --verbose ."
  - name: flake8
    python: 3.8
    before_install: []
    env:
    - TEST_CMD="flake8 src/pyconnect/"
  - name: '3.6'
    python: 3.6
  - name: '3.7'
    python: 3.7
  - name: '3.8'
